version: 4.0.{build}
max_jobs: 1
image: Visual Studio 2017
configuration: Release
init:
- ps: '#$blockRdp = $true; iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1"))'
environment:
  SECURE_GITHUB_TOKEN:
    secure: yf7Him/R+dJ/gKfZR+Hqc3cwuZVQMWOuR1WZ9XuMwmkWyQD6yDIqUaFIBzcr0oEW
  APPVEYOR_CACHE_SKIP_RESTORE: false
  ENABLE_REMOTE_DESKTOP: false
cache:
- C:\projects\botan\botan.lib
- C:\projects\botan\build\include
- C:\Users\appveyor\.cargo

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host x86_64-pc-windows-msvc --default-toolchain stable -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

before_build:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    
    PATH=C:\Python36-x64;%PATH%

    IF EXIST C:\projects\botan (echo "Using botan build from appveyor cache") ELSE (cd .. && git clone https://github.com/randombit/botan botan && cd botan && git checkout 2.6.0 && python configure.py --disable-shared-library --msvc-runtime=MT --cxxflags="/O2 /Oi /D_ENABLE_EXTENDED_ALIGNED_STORAGE" && nmake && cd ..\playbook-creator\)

    cmake -G "Visual Studio 15 2017 Win64" -D BOOST_ROOT=C:\Libraries\boost_1_65_1 -D Qt5_DIR=C:\Qt\5.11\msvc2017_64\lib\cmake\Qt5 -D Qt5Widgets_DIR=C:\Qt\5.11\msvc2017_64\lib\cmake\Qt5Widgets -D Qt5PrintSupport_DIR=C:\Qt\5.11\msvc2017_64\lib\cmake\Qt5PrintSupport -D BOTAN_LIBRARY=C:\projects\botan\botan.lib -D BOTAN_INCLUDE_DIR=C:\projects\botan\build\include .

    echo "starting build..."
build:
  project: ALL_BUILD.vcxproj
  verbosity: normal
after_build:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

    C:\Qt\5.11\msvc2017_64\bin\windeployqt.exe --release --pdb --compiler-runtime "C:\projects\playbook-creator\bin\Release"

    cd bin\Release\ && tests.exe -- --test-base-dir "..\..\test" && cd ..\..

    "C:\Program Files (x86)\Inno Setup 5\ISCC" C:\projects\playbook-creator\innosetup.iss
artifacts:
- path: bin\release\PlaybookCreator.exe
  name: PlaybookCreator.exe
- path: bin\PlaybookCreatorSetup.exe
  name: PlaybookCreatorSetup.exe
deploy_script:
- ps: >-
    $TOKEN = $env:SECURE_GITHUB_TOKEN

    bash deploy.sh bin/PlaybookCreatorSetup.exe PlaybookCreatorSetup.exe "PlaybookCreator for Windows" $TOKEN
on_finish:
- ps: >-
    if($env:ENABLE_REMOTE_DESKTOP -eq $true) {$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))}
